package com.ooteco.bean;

import java.util.Date;

public class Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.id
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.mobile
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.passwd
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.nick
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.email
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.gender
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.birthday
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.header
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String header;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.last_login_ip
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.last_login_dt
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private Date lastLoginDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.status
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.annaul_income
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String annaulIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.urpi
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String urpi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.wx_feed
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String wxFeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.wx_openid
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String wxOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.login_error_count
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private Integer loginErrorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.create_by
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.create_date
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.update_by
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.update_date
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.remarks
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.del_flag
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.opmode
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String opmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.my_guide_flag
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String myGuideFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.name
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.id_card
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.bank_card_count
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private Integer bankCardCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.trade_pwd
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private String tradePwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.review_res
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private Integer reviewRes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.is_show_share
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private Integer isShowShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.is_open_account
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private Integer isOpenAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_account.is_bind_card
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    private Integer isBindCard;

    /**
     * 帐管家开户绑卡成功标识
     */
    private Integer isZgjOpenAccount;

    public Integer getIsZgjOpenAccount() {
        return isZgjOpenAccount;
    }

    public void setIsZgjOpenAccount(Integer isZgjOpenAccount) {
        this.isZgjOpenAccount = isZgjOpenAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.id
     *
     * @return the value of s_account.id
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.id
     *
     * @param id the value for s_account.id
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.mobile
     *
     * @return the value of s_account.mobile
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.mobile
     *
     * @param mobile the value for s_account.mobile
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.passwd
     *
     * @return the value of s_account.passwd
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.passwd
     *
     * @param passwd the value for s_account.passwd
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.nick
     *
     * @return the value of s_account.nick
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.nick
     *
     * @param nick the value for s_account.nick
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.email
     *
     * @return the value of s_account.email
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.email
     *
     * @param email the value for s_account.email
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.gender
     *
     * @return the value of s_account.gender
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.gender
     *
     * @param gender the value for s_account.gender
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.birthday
     *
     * @return the value of s_account.birthday
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.birthday
     *
     * @param birthday the value for s_account.birthday
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.header
     *
     * @return the value of s_account.header
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.header
     *
     * @param header the value for s_account.header
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.last_login_ip
     *
     * @return the value of s_account.last_login_ip
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.last_login_ip
     *
     * @param lastLoginIp the value for s_account.last_login_ip
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.last_login_dt
     *
     * @return the value of s_account.last_login_dt
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public Date getLastLoginDt() {
        return lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.last_login_dt
     *
     * @param lastLoginDt the value for s_account.last_login_dt
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setLastLoginDt(Date lastLoginDt) {
        this.lastLoginDt = lastLoginDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.status
     *
     * @return the value of s_account.status
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.status
     *
     * @param status the value for s_account.status
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.annaul_income
     *
     * @return the value of s_account.annaul_income
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getAnnaulIncome() {
        return annaulIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.annaul_income
     *
     * @param annaulIncome the value for s_account.annaul_income
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setAnnaulIncome(String annaulIncome) {
        this.annaulIncome = annaulIncome == null ? null : annaulIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.urpi
     *
     * @return the value of s_account.urpi
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getUrpi() {
        return urpi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.urpi
     *
     * @param urpi the value for s_account.urpi
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setUrpi(String urpi) {
        this.urpi = urpi == null ? null : urpi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.wx_feed
     *
     * @return the value of s_account.wx_feed
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getWxFeed() {
        return wxFeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.wx_feed
     *
     * @param wxFeed the value for s_account.wx_feed
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setWxFeed(String wxFeed) {
        this.wxFeed = wxFeed == null ? null : wxFeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.wx_openid
     *
     * @return the value of s_account.wx_openid
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.wx_openid
     *
     * @param wxOpenid the value for s_account.wx_openid
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.login_error_count
     *
     * @return the value of s_account.login_error_count
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public Integer getLoginErrorCount() {
        return loginErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.login_error_count
     *
     * @param loginErrorCount the value for s_account.login_error_count
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setLoginErrorCount(Integer loginErrorCount) {
        this.loginErrorCount = loginErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.create_by
     *
     * @return the value of s_account.create_by
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.create_by
     *
     * @param createBy the value for s_account.create_by
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.create_date
     *
     * @return the value of s_account.create_date
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.create_date
     *
     * @param createDate the value for s_account.create_date
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.update_by
     *
     * @return the value of s_account.update_by
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.update_by
     *
     * @param updateBy the value for s_account.update_by
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.update_date
     *
     * @return the value of s_account.update_date
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.update_date
     *
     * @param updateDate the value for s_account.update_date
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.remarks
     *
     * @return the value of s_account.remarks
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.remarks
     *
     * @param remarks the value for s_account.remarks
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.del_flag
     *
     * @return the value of s_account.del_flag
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.del_flag
     *
     * @param delFlag the value for s_account.del_flag
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.opmode
     *
     * @return the value of s_account.opmode
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getOpmode() {
        return opmode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.opmode
     *
     * @param opmode the value for s_account.opmode
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setOpmode(String opmode) {
        this.opmode = opmode == null ? null : opmode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.my_guide_flag
     *
     * @return the value of s_account.my_guide_flag
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getMyGuideFlag() {
        return myGuideFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.my_guide_flag
     *
     * @param myGuideFlag the value for s_account.my_guide_flag
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setMyGuideFlag(String myGuideFlag) {
        this.myGuideFlag = myGuideFlag == null ? null : myGuideFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.name
     *
     * @return the value of s_account.name
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.name
     *
     * @param name the value for s_account.name
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.id_card
     *
     * @return the value of s_account.id_card
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.id_card
     *
     * @param idCard the value for s_account.id_card
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.bank_card_count
     *
     * @return the value of s_account.bank_card_count
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public Integer getBankCardCount() {
        return bankCardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.bank_card_count
     *
     * @param bankCardCount the value for s_account.bank_card_count
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setBankCardCount(Integer bankCardCount) {
        this.bankCardCount = bankCardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.trade_pwd
     *
     * @return the value of s_account.trade_pwd
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public String getTradePwd() {
        return tradePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.trade_pwd
     *
     * @param tradePwd the value for s_account.trade_pwd
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setTradePwd(String tradePwd) {
        this.tradePwd = tradePwd == null ? null : tradePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.review_res
     *
     * @return the value of s_account.review_res
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public Integer getReviewRes() {
        return reviewRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.review_res
     *
     * @param reviewRes the value for s_account.review_res
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setReviewRes(Integer reviewRes) {
        this.reviewRes = reviewRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.is_show_share
     *
     * @return the value of s_account.is_show_share
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public Integer getIsShowShare() {
        return isShowShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.is_show_share
     *
     * @param isShowShare the value for s_account.is_show_share
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setIsShowShare(Integer isShowShare) {
        this.isShowShare = isShowShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.is_open_account
     *
     * @return the value of s_account.is_open_account
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public Integer getIsOpenAccount() {
        return isOpenAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.is_open_account
     *
     * @param isOpenAccount the value for s_account.is_open_account
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setIsOpenAccount(Integer isOpenAccount) {
        this.isOpenAccount = isOpenAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_account.is_bind_card
     *
     * @return the value of s_account.is_bind_card
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public Integer getIsBindCard() {
        return isBindCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_account.is_bind_card
     *
     * @param isBindCard the value for s_account.is_bind_card
     *
     * @mbggenerated Wed Jan 18 16:47:04 CST 2017
     */
    public void setIsBindCard(Integer isBindCard) {
        this.isBindCard = isBindCard;
    }
}